version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20 #AWS CLI functionality
  kubernetes: circleci/kubernetes@0.11.0
  aws-eks: circleci/aws-eks@0.2.0 #EKS (Managed Kubernetes Cluster)
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  pylint:
    working_directory: /app
    steps:
      - checkout
      - run: pip3 install pylint pylint_django
      - run: ls
      - run: find . -type f -name "*.py" | grep -v 'migrations' | grep -v 'tests' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django --disable=no-member

  deployment_checklist:
    working_directory: /app
    docker:
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - run: python manage.py check --deploy --fail-level ERROR

workflows:
  version: 2.1
  backend_tag_for_release:
    jobs:
      - pylint
      - deployment_checklist
