version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20 #AWS CLI functionality
  kubernetes: circleci/kubernetes@0.11.0
  aws-eks: circleci/aws-eks@0.2.0 #EKS (Managed Kubernetes Cluster)
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  docker-publish:
    docker-registry: ${ARTIFACTORY_REGISTRY}
    repository: docker-local
    docker-tag: "reservation:latest/${ARTIFACTORY_REGISTRY}"
    docker-steps:
      - run: |
          docker build -t ${DOCKERTAG} .
          mkdir -p saved_images
          docker save -o saved_images/docker_image_backend.tar $DOCKERTAG
      - persist_to_workspace:
          root: saved_images
          paths:
            - docker_image_backend.tar

  pylint:
    working_directory: /app
    docker:
      - image: reservation:latest/${ARTIFACTORY_REGISTRY}
    steps:
      - checkout
      - run: pip3 install pylint pylint_django
      - run: ls
      - run: find . -type f -name "*.py" | grep -v 'migrations' | grep -v 'tests' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django --disable=no-member

  deployment-checklist:
    working_directory: /app
    docker:
      - image: reservation:latest/${ARTIFACTORY_REGISTRY}
    steps:
      - checkout
      - run: python manage.py check --deploy --fail-level ERROR

workflows:
  version: 2.1
  backend_tag_for_release:
    jobs:
      - docker-publish
      - pylint
      - deployment-checklist
      # - deploy-backend
