version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.2
  aws-cli: circleci/aws-cli@0.1.20 #AWS CLI functionality
  kubernetes: circleci/kubernetes@0.11.0
  aws-eks: circleci/aws-eks@0.2.0 #EKS (Managed Kubernetes Cluster)
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  pylint:
    working_directory: /app
    docker:
      - image: reservation:latest/${ARTIFACTORY_REGISTRY}
    steps:
      - checkout
      - run: pip3 install pylint pylint_django
      - run: ls
      - run: find . -type f -name "*.py" | grep -v 'migrations' | grep -v 'tests' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django --disable=no-member

  deployment-checklist:
    working_directory: /app
    docker:
      - image: reservation:latest/${ARTIFACTORY_REGISTRY}
    steps:
      - checkout
      - run: python manage.py check --deploy --fail-level ERROR

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - pylint:
          requires:
            - aws-ecr/build-and-push-image
      - deployment-checklist:
          requires:
            - aws-ecr/build-and-push-image
